### ISSUE TITLE
import-tfc-state.sh curl authorization

### ISSUE THREAD

**Issue by jandroav** [spacelift-io/spacelift-migration-kit#17]
Added --header "Authorization: Bearer $TFC_TOKEN" to the second curl command because the script fails with a 401 while running the second curl command:

![image](https://github.com/spacelift-io/spacelift-migration-kit/assets/67458478/611fa133-96ce-4f25-b356-6eda47cf1628)

PR here: https://github.com/spacelift-io/spacelift-migration-kit/pull/16

**Comment by jmfontaine** [comment]
I merged the PR. Thanks @jandroav!
