### ISSUE TITLE
Variable names used across multiple workspaces cause conflict in generated terraform

### ISSUE THREAD

**Issue by roccato** [spacelift-io/spacelift-migration-kit#4]
If multiple workspaces I am importing from tfc share variable names, such as `aws_access_key` then the generated terraform for the migration will throw Duplicate Resource error.

**Comment by jmfontaine** [comment]
Thanks for reporting this. We will look into it.

**Comment by jmfontaine** [comment]
@roccato This issue is now fixed. Thanks for reporting it!
